AIUTS/urls.py
from django.urls import path
from . import views

app_name = 'AIUTS'
urlpatterns = [
    path('', views.userAccountList.as_view(), name='index'),
    path('acc/<str:pk>/', views.userbalanceView.as_view(), name='userbalance'),
    path('transactionList/', views.transactionList.as_view(), name='transactionList'),
    path('requestList/', views.requestList.as_view(), name='requestList'),
    path('pendingList/', views.pendingList.as_view(), name='pendingList'),
    path('Approve/<int:pk>', views.Approve.as_view(), name='Approve'),
    path('addAccount/', views.CreateAccountView.as_view(), name='addAccount'),
    path('addTransaction/', views.CreateTransactionView.as_view(), name='addTransaction'),
    path('paymentRequest/', views.makeRequest.as_view(), name='paymentRequest'),
    path('deposit/', views.makeDeposit.as_view(), name="deposit"),
]

AiuTransactionSystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('AIUTS.urls')),
    path('controller/', include('controller.urls'))
]

controller/urls.py
from django.urls import path
from . import views

app_name = 'controller'
urlpatterns = [
    path('', views.indexViews.as_view(), name='index'),
    path('Approve/<int:pk>', views.Approve.as_view(), name='Approve'),
]

controller/models.py
from django.db import models

# Create your models here.

controller/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from AIUTS.models import DepositRequest
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

class indexViews(PermissionRequiredMixin, LoginRequiredMixin, generic.ListView):
    permission_required = 'depositrequest.view_depositrequest'
    template_name = 'controller/index.html'
    context_object_name = 'requests'

    def get_queryset(self):
        return DepositRequest.objects.filter(RequestStatus="Pending").order_by('RequestTime')

class Approve(PermissionRequiredMixin, LoginRequiredMixin, generic.UpdateView):
    permission_required = 'depositrequest.change_depositrequest'
    model = DepositRequest
    fields = ['RequestStatus']
    template_name = 'controller/edit.html'
    success_url = '/controller/'

controller/templates/controller/bases.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
        <title>AIUTS</title>

        <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
</head>
<body>

    {% block content %}
    {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block js %}
    {% endblock js %}

</body>
</html>

controller/templates/controller/edit.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap');
html {
    font-family: 'Poppins', sans-serif;
    position: relative;
    width: 100%;
    height: 100vh;
}

form {
    position: absolute;
    top: 20%;
    left: 800px;
}

h1 {
    text-transform: uppercase;
}

select {
    width: 100px;
    height: 35px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border: none;
}

button {
    background-color: #d47304;
    width: 100px;
    height: 35px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border: none;
    animation: background-color 0.3s;
}

button:hover {
    background-color: #6bff39;
}


</style>

<form method="post" >
    
    {% csrf_token %}
    <h1>{{ form.as_p }}</h1>

    <div>
        <button  type="submit">Save</button><br>
    </div>  
    
</form>

controller/templates/controller/index.html
{% extends "controller/bases.html" %} {% block content %}

<p></p>

<h1 class="text-center">All Deposit Request</h1>
<p></p>

<div class="container">
  <p class="logout"><a class="logoutbtn" href="{% url 'logout'%}">Logout</a></p>
  <table class="table" id="depositRequest">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Time</th>
        <th scope="col">Amount</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for request in requests%}
      <tr>
        <th scope="row">{{request.DepositRequestID}}</th>
        <td>{{ request.RequestReceiver }}</td>
        <td>{{ request.RequestTime }}</td>
        <td>{{ request.RequestAmount }}</td>
        <td>{{ request.RequestStatus }}</td>
        <td>
          <a href="{% url 'controller:Approve' request.DepositRequestID%}"
            >Approve</a
          >
        </td>
      </tr>
      {% empty %}
      <p id="empty">No Deposit Request in a Moment</p>
      {% endfor %}
    </tbody>
  </table>
  <br />
</div>

{% endblock %} {% block js %}
<script>
  function fetchdata() {
    $.ajax({
      url: "{% url 'controller:index' %}",
      type: "GET",
      success: function (data) {
        balance = data.slice(
          data.indexOf("Balance:") + 34,
          data.indexOf("/span") - 1
        );
        requesttable = data.slice(
          data.indexOf("table") - 1,
          data.indexOf("/table") + 10
        );
        $("#depositRequest").replaceWith(requesttable);
        $("#empty").remove();
      },
    });
  }

  $(document).ready(function () {
    setInterval(fetchdata, 5000);
  });
</script>

{% endblock js %}